/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lifenotemusiccenter_official;

import javax.swing.JOptionPane;

/**
 *
 * @author Tharindu Munasinghe
 */
public class BasicCalculator extends javax.swing.JFrame {

    String sign = "";
    String firstValue = "";

    /**
     * Creates new form UI
     */
    public BasicCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtValueField = new javax.swing.JTextField();
        Jbtn1 = new javax.swing.JButton();
        Jbtn2 = new javax.swing.JButton();
        Jbtn3 = new javax.swing.JButton();
        Jbtn4 = new javax.swing.JButton();
        Jbtn5 = new javax.swing.JButton();
        Jbtn6 = new javax.swing.JButton();
        Jbtn7 = new javax.swing.JButton();
        Jbtn8 = new javax.swing.JButton();
        Jbtn9 = new javax.swing.JButton();
        Jbtn0 = new javax.swing.JButton();
        JbtnAdd = new javax.swing.JButton();
        JbtnMultiply = new javax.swing.JButton();
        JbtnSubstract = new javax.swing.JButton();
        JbtnDivide = new javax.swing.JButton();
        JbtnEqual = new javax.swing.JButton();
        Jbtn00 = new javax.swing.JButton();
        JbtnDOT = new javax.swing.JButton();
        JbtnClearField = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LNMC - Basic Calculator");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtValueField.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        txtValueField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        getContentPane().add(txtValueField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 377, 46));

        Jbtn1.setBackground(new java.awt.Color(255, 204, 0));
        Jbtn1.setFont(new java.awt.Font("Chosence", 0, 18)); // NOI18N
        Jbtn1.setText("1");
        Jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 84, 37));

        Jbtn2.setBackground(new java.awt.Color(255, 204, 0));
        Jbtn2.setFont(new java.awt.Font("Chosence", 0, 18)); // NOI18N
        Jbtn2.setText("2");
        Jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 84, 37));

        Jbtn3.setBackground(new java.awt.Color(255, 204, 0));
        Jbtn3.setFont(new java.awt.Font("Chosence", 0, 18)); // NOI18N
        Jbtn3.setText("3");
        Jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 84, 37));

        Jbtn4.setBackground(new java.awt.Color(255, 204, 0));
        Jbtn4.setFont(new java.awt.Font("Chosence", 0, 18)); // NOI18N
        Jbtn4.setText("4");
        Jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 84, 37));

        Jbtn5.setBackground(new java.awt.Color(255, 204, 0));
        Jbtn5.setFont(new java.awt.Font("Chosence", 0, 18)); // NOI18N
        Jbtn5.setText("5");
        Jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 84, 37));

        Jbtn6.setBackground(new java.awt.Color(255, 204, 0));
        Jbtn6.setFont(new java.awt.Font("Chosence", 0, 18)); // NOI18N
        Jbtn6.setText("6");
        Jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 84, 37));

        Jbtn7.setBackground(new java.awt.Color(255, 204, 0));
        Jbtn7.setFont(new java.awt.Font("Chosence", 0, 18)); // NOI18N
        Jbtn7.setText("7");
        Jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 84, 35));

        Jbtn8.setBackground(new java.awt.Color(255, 204, 0));
        Jbtn8.setFont(new java.awt.Font("Chosence", 0, 18)); // NOI18N
        Jbtn8.setText("8");
        Jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 84, 35));

        Jbtn9.setBackground(new java.awt.Color(255, 204, 0));
        Jbtn9.setFont(new java.awt.Font("Chosence", 0, 18)); // NOI18N
        Jbtn9.setText("9");
        Jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 84, -1));

        Jbtn0.setBackground(new java.awt.Color(255, 204, 0));
        Jbtn0.setFont(new java.awt.Font("Chosence", 0, 18)); // NOI18N
        Jbtn0.setText("0");
        Jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn0ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 218, 84, 37));

        JbtnAdd.setBackground(new java.awt.Color(255, 204, 0));
        JbtnAdd.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        JbtnAdd.setText("+");
        JbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 49, -1));

        JbtnMultiply.setBackground(new java.awt.Color(255, 204, 0));
        JbtnMultiply.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        JbtnMultiply.setText("X");
        JbtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnMultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        JbtnSubstract.setBackground(new java.awt.Color(255, 204, 0));
        JbtnSubstract.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        JbtnSubstract.setText("-");
        JbtnSubstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSubstractActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnSubstract, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 48, -1));

        JbtnDivide.setBackground(new java.awt.Color(255, 204, 0));
        JbtnDivide.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        JbtnDivide.setText("÷");
        JbtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 48, -1));

        JbtnEqual.setBackground(new java.awt.Color(255, 204, 0));
        JbtnEqual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JbtnEqual.setText("=");
        JbtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnEqualActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 100, 42));

        Jbtn00.setBackground(new java.awt.Color(255, 204, 0));
        Jbtn00.setFont(new java.awt.Font("Chosence", 0, 18)); // NOI18N
        Jbtn00.setText("00");
        Jbtn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn00ActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn00, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 218, 84, 37));

        JbtnDOT.setBackground(new java.awt.Color(255, 204, 0));
        JbtnDOT.setFont(new java.awt.Font("Chosence", 0, 18)); // NOI18N
        JbtnDOT.setText(".");
        JbtnDOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDOTActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnDOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 218, 84, 37));

        JbtnClearField.setBackground(new java.awt.Color(255, 204, 0));
        JbtnClearField.setFont(new java.awt.Font("Chosence", 0, 18)); // NOI18N
        JbtnClearField.setText("C");
        JbtnClearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnClearFieldActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnClearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 218, 98, 37));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 450, 290));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-413)/2, (screenSize.height-305)/2, 413, 305);
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn1ActionPerformed
        String s = txtValueField.getText();
        txtValueField.setText(s + "1");
    }//GEN-LAST:event_Jbtn1ActionPerformed

    private void Jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn2ActionPerformed
        String s = txtValueField.getText();
        txtValueField.setText(s + "2");
    }//GEN-LAST:event_Jbtn2ActionPerformed

    private void Jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn3ActionPerformed
        String s = txtValueField.getText();
        txtValueField.setText(s + "3");
    }//GEN-LAST:event_Jbtn3ActionPerformed

    private void Jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn4ActionPerformed
        String s = txtValueField.getText();
        txtValueField.setText(s + "4");
    }//GEN-LAST:event_Jbtn4ActionPerformed

    private void Jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn5ActionPerformed
        String s = txtValueField.getText();
        txtValueField.setText(s + "5");
    }//GEN-LAST:event_Jbtn5ActionPerformed

    private void Jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn6ActionPerformed
        String s = txtValueField.getText();
        txtValueField.setText(s + "6");
    }//GEN-LAST:event_Jbtn6ActionPerformed

    private void Jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn7ActionPerformed
        String s = txtValueField.getText();
        txtValueField.setText(s + "7");
    }//GEN-LAST:event_Jbtn7ActionPerformed

    private void Jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn8ActionPerformed
        String s = txtValueField.getText();
        txtValueField.setText(s + "8");
    }//GEN-LAST:event_Jbtn8ActionPerformed

    private void Jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn9ActionPerformed
        String s = txtValueField.getText();
        txtValueField.setText(s + "9");
    }//GEN-LAST:event_Jbtn9ActionPerformed

    private void Jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn0ActionPerformed
        String s = txtValueField.getText();
        txtValueField.setText(s + "0");
    }//GEN-LAST:event_Jbtn0ActionPerformed

    private void JbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnAddActionPerformed
        sign = "+";
        firstValue = txtValueField.getText();
        txtValueField.setText("");
    }//GEN-LAST:event_JbtnAddActionPerformed

    private void JbtnSubstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSubstractActionPerformed
        sign = "-";
        firstValue = txtValueField.getText();
        txtValueField.setText("");
    }//GEN-LAST:event_JbtnSubstractActionPerformed

    private void JbtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnMultiplyActionPerformed
        sign = "*";
        firstValue = txtValueField.getText();
        txtValueField.setText("");
    }//GEN-LAST:event_JbtnMultiplyActionPerformed

    private void JbtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDivideActionPerformed
        sign = "/";
        firstValue = txtValueField.getText();
        txtValueField.setText("");
    }//GEN-LAST:event_JbtnDivideActionPerformed

    private void JbtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnEqualActionPerformed
//        firstValue = "0";
        double d1 = Double.parseDouble(firstValue);
        double d2 = Double.parseDouble(txtValueField.getText());
        double total = 0.0;
        if (sign.equals("+")) {
            total = d1 + d2;
        } else if (sign.equals("-")) {
            total = d1 - d2;
        } else if (sign.equals("*")) {
            total = d1 * d2;
        } else if (sign.equals("/")) {
            total = d1 / d2;
        } else {
            JOptionPane.showMessageDialog(null, "Operater is not defined");
        }
        txtValueField.setText(total + "");
        sign = "";
        firstValue = "0";
    }//GEN-LAST:event_JbtnEqualActionPerformed

    private void Jbtn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn00ActionPerformed
        String s = txtValueField.getText();
        txtValueField.setText(s + "00");
    }//GEN-LAST:event_Jbtn00ActionPerformed

    private void JbtnDOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDOTActionPerformed
        String s = txtValueField.getText();
        txtValueField.setText(s + ".");
    }//GEN-LAST:event_JbtnDOTActionPerformed

    private void JbtnClearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnClearFieldActionPerformed
        txtValueField.setText("");
    }//GEN-LAST:event_JbtnClearFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BasicCalculator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn0;
    private javax.swing.JButton Jbtn00;
    private javax.swing.JButton Jbtn1;
    private javax.swing.JButton Jbtn2;
    private javax.swing.JButton Jbtn3;
    private javax.swing.JButton Jbtn4;
    private javax.swing.JButton Jbtn5;
    private javax.swing.JButton Jbtn6;
    private javax.swing.JButton Jbtn7;
    private javax.swing.JButton Jbtn8;
    private javax.swing.JButton Jbtn9;
    private javax.swing.JButton JbtnAdd;
    private javax.swing.JButton JbtnClearField;
    private javax.swing.JButton JbtnDOT;
    private javax.swing.JButton JbtnDivide;
    private javax.swing.JButton JbtnEqual;
    private javax.swing.JButton JbtnMultiply;
    private javax.swing.JButton JbtnSubstract;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtValueField;
    // End of variables declaration//GEN-END:variables
}
