/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lifenotemusiccenter_official;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lifenotemusiccenter_official.Instruments;
import lifenotemusiccenter_official.MyConn;
import lifenotemusiccenter_official.Purchase;
import lifenotemusiccenter_official.Dashboard;

/**
 *
 * @author lenovo
 */
public class Books extends javax.swing.JFrame {

    /**
     * Creates new form books
     */
    public Books() {
        initComponents();
        search();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSearch = new javax.swing.ButtonGroup();
        buttonGroupFilter = new javax.swing.ButtonGroup();
        buttonGroupIN_UP_DEL = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        JbtnInsert = new javax.swing.JButton();
        JbtnUpdate = new javax.swing.JButton();
        JbtnDelete = new javax.swing.JButton();
        JRB_BName = new javax.swing.JRadioButton();
        JRB_BAuthor = new javax.swing.JRadioButton();
        JRB_BType = new javax.swing.JRadioButton();
        JRB_Bcheap = new javax.swing.JRadioButton();
        JRB_BExpensive = new javax.swing.JRadioButton();
        JbtnFilterSearch1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JtblSearch = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        JbtnInstruments = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JbtnPurchase = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        JbtnAccessories = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        JBTN_Dashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LNMC - Books");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Orbitron", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Books");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Item Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 204, 0)));
        jPanel1.setOpaque(false);

        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("ID");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Name");

        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Author");

        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("Item Type");

        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });

        txtPrice.setName("");
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("Price (LKR.)");

        jLabel10.setForeground(new java.awt.Color(255, 204, 0));
        jLabel10.setText("Stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Functions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 204, 0)));
        jPanel3.setOpaque(false);

        JbtnInsert.setBackground(new java.awt.Color(51, 255, 51));
        JbtnInsert.setText("Insert");
        JbtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnInsertActionPerformed(evt);
            }
        });

        JbtnUpdate.setBackground(new java.awt.Color(51, 255, 51));
        JbtnUpdate.setText("Update");
        JbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnUpdateActionPerformed(evt);
            }
        });

        JbtnDelete.setBackground(new java.awt.Color(255, 0, 0));
        JbtnDelete.setText("Delete");
        JbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDeleteActionPerformed(evt);
            }
        });

        buttonGroupSearch.add(JRB_BName);
        JRB_BName.setForeground(new java.awt.Color(255, 204, 0));
        JRB_BName.setText("Name");
        JRB_BName.setOpaque(false);
        JRB_BName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_BNameActionPerformed(evt);
            }
        });

        buttonGroupSearch.add(JRB_BAuthor);
        JRB_BAuthor.setForeground(new java.awt.Color(255, 204, 0));
        JRB_BAuthor.setText("Author");
        JRB_BAuthor.setOpaque(false);
        JRB_BAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_BAuthorActionPerformed(evt);
            }
        });

        buttonGroupSearch.add(JRB_BType);
        JRB_BType.setForeground(new java.awt.Color(255, 204, 0));
        JRB_BType.setText("Type");
        JRB_BType.setOpaque(false);
        JRB_BType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_BTypeActionPerformed(evt);
            }
        });

        buttonGroupFilter.add(JRB_Bcheap);
        JRB_Bcheap.setForeground(new java.awt.Color(255, 204, 0));
        JRB_Bcheap.setText("Cheap");
        JRB_Bcheap.setOpaque(false);
        JRB_Bcheap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_BcheapActionPerformed(evt);
            }
        });

        buttonGroupFilter.add(JRB_BExpensive);
        JRB_BExpensive.setForeground(new java.awt.Color(255, 204, 0));
        JRB_BExpensive.setText("Expensive");
        JRB_BExpensive.setOpaque(false);
        JRB_BExpensive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_BExpensiveActionPerformed(evt);
            }
        });

        JbtnFilterSearch1.setBackground(new java.awt.Color(255, 255, 51));
        JbtnFilterSearch1.setText("FilterSearch");
        JbtnFilterSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnFilterSearch1ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JbtnInsert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JbtnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JbtnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JbtnFilterSearch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JRB_BType)
                            .addComponent(JRB_BName)
                            .addComponent(JRB_BAuthor))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(JRB_Bcheap, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(JRB_BExpensive, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(JbtnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JbtnFilterSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JRB_BName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRB_Bcheap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JRB_BAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRB_BExpensive))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JRB_BType, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Search / Find", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 204, 0)));
        jPanel4.setOpaque(false);

        JtblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Author", "Type", "Price", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JtblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtblSearchMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JtblSearch);
        JtblSearch.getColumnModel().getColumn(0).setResizable(false);
        JtblSearch.getColumnModel().getColumn(1).setResizable(false);
        JtblSearch.getColumnModel().getColumn(2).setResizable(false);
        JtblSearch.getColumnModel().getColumn(3).setResizable(false);
        JtblSearch.getColumnModel().getColumn(4).setResizable(false);
        JtblSearch.getColumnModel().getColumn(5).setResizable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Jump To"));

        JbtnInstruments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifenotemusiccenter_official/Instruments icon.png"))); // NOI18N
        JbtnInstruments.setBorder(null);
        JbtnInstruments.setContentAreaFilled(false);
        JbtnInstruments.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JbtnInstruments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnInstrumentsActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Instruments");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JbtnPurchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifenotemusiccenter_official/purchase icon.png"))); // NOI18N
        JbtnPurchase.setBorder(null);
        JbtnPurchase.setContentAreaFilled(false);
        JbtnPurchase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JbtnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnPurchaseActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Purchase");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JbtnAccessories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifenotemusiccenter_official/accessories icon.png"))); // NOI18N
        JbtnAccessories.setBorder(null);
        JbtnAccessories.setContentAreaFilled(false);
        JbtnAccessories.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JbtnAccessories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnAccessoriesActionPerformed(evt);
            }
        });

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Accessories");
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JBTN_Dashboard.setBackground(new java.awt.Color(255, 0, 0));
        JBTN_Dashboard.setFont(new java.awt.Font("Ice kingdom", 0, 24)); // NOI18N
        JBTN_Dashboard.setText("Dashboard");
        JBTN_Dashboard.setOpaque(false);
        JBTN_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_DashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JbtnInstruments, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JbtnAccessories, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JbtnPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JBTN_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JbtnAccessories, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(JbtnInstruments, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JBTN_Dashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JbtnPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel31)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-971)/2, (screenSize.height-534)/2, 971, 534);
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnInsertActionPerformed
        try {
            String Insert = "INSERT INTO `lifenotemusiccenter`.`books` (`Name`,`Author`,`Type`,`Unit Price`,`Stock`) "
                    + "values ('" + txtName.getText() + "','" + txtAuthor.getText() + "',"
                    + "'" + txtType.getText() + "','" + txtPrice.getText() + "','" + txtStock.getText() + "')";
            MyConn.save(Insert);

            searchIN_UP_DEL();
            JOptionPane.showMessageDialog(this, "The item successfully "
                    + "added to the database");
            int row = JtblSearch.getRowCount();
            row--;
            String id = (String) JtblSearch.getValueAt(row, 0);
            txtId.setText(id);
            UP_toGRN();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_JbtnInsertActionPerformed
    private void JbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnUpdateActionPerformed
        try {
            txtId.enableInputMethods(false);

            int rownumber = JtblSearch.getSelectedRow();
            txtId.setText(JtblSearch.getValueAt(rownumber, 0) + "");

            String SCurrentStock = (String) JtblSearch.getValueAt(rownumber, 5);
            int CurrentStock = Integer.parseInt(SCurrentStock);

            int UpdateStock = Integer.parseInt(txtStock.getText());
            int NewStock = CurrentStock + UpdateStock;

            String up = "Update `books` set Name = '" + txtName.getText() + "',"
                    + "Author = '" + txtAuthor.getText() + "',Type = '" + txtType.getText() + "',"
                    + "`Unit Price` = '" + txtPrice.getText() + "',Stock = '" + NewStock + "' "
                    + "where id='" + txtId.getText() + "'";
            MyConn.save(up);
            searchIN_UP_DEL();
            UP_toGRN();
            JOptionPane.showMessageDialog(this, "The item successfully updated");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_JbtnUpdateActionPerformed

    private void JbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDeleteActionPerformed
        try {
            txtId.enableInputMethods(false);

            int rownumber = JtblSearch.getSelectedRow();
            int stock = Integer.parseInt(txtStock.getText());
            stock = stock - 2 * stock;

            String delete = "Delete from books where ID = '"
                    + (JtblSearch.getValueAt(rownumber, 0) + "") + "'";
            MyConn.save(delete);

            searchIN_UP_DEL();

            try {
                String sqlINUP = "INSERT into grn (`DB Table`, `Item ID`, `Added Stock`,"
                        + "`Other changes_Name`, `Other changese_Brand_Author`,"
                        + "`Other changes_Type`, `Other changes_Unit Price`, `Date and Time`)"
                        + "values('Books','" + txtId.getText() + "','" + stock + "',"
                        + "'" + txtName.getText() + "','" + txtAuthor.getText() + "',"
                        + "'" + txtType.getText() + "','" + txtPrice.getText() + "',current_timestamp)";
                MyConn.save(sqlINUP);
            } catch (Exception e) {
                e.printStackTrace();
            }

            JOptionPane.showMessageDialog(this, "The item successfully deleted");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_JbtnDeleteActionPerformed

    private void JbtnInstrumentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnInstrumentsActionPerformed
        new Instruments().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JbtnInstrumentsActionPerformed

    private void JbtnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnPurchaseActionPerformed
        new Dashboard().setVisible(true);        
        new Purchase().setVisible(true);
        new Purchase().requestFocusInWindow();
        this.dispose();
    }//GEN-LAST:event_JbtnPurchaseActionPerformed

    private void JbtnAccessoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnAccessoriesActionPerformed
        new Accessories().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JbtnAccessoriesActionPerformed

    private void JtblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtblSearchMouseClicked
        int row = JtblSearch.getSelectedRow();
        txtId.setText(JtblSearch.getValueAt(row, 0) + "");
        txtName.setText(JtblSearch.getValueAt(row, 1) + "");
        txtAuthor.setText(JtblSearch.getValueAt(row, 2) + "");
        txtType.setText(JtblSearch.getValueAt(row, 3) + "");
        txtPrice.setText(JtblSearch.getValueAt(row, 4) + "");
        txtId.setEditable(false);
    }//GEN-LAST:event_JtblSearchMouseClicked

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        search();
    }//GEN-LAST:event_txtNameKeyReleased

    private void JbtnFilterSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnFilterSearch1ActionPerformed
        DefaultTableModel df = (DefaultTableModel) JtblSearch.getModel();
        df.setRowCount(0);

        if (JRB_BName.isSelected()) {
            try {
                String search = "select*from books where name like"
                        + "'" + txtName.getText() + "%'";
                ResultSet rs1 = MyConn.search(search);
                df.setRowCount(0);
                while (rs1.next()) {
                    Vector v = new Vector();
                    v.add(rs1.getString("ID"));
                    v.add(rs1.getString("Name"));
                    v.add(rs1.getString("Author"));
                    v.add(rs1.getString("Type"));
                    v.add(rs1.getString("Unit Price"));
                    v.add(rs1.getString("Stock"));
                    df.addRow(v);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (JRB_BAuthor.isSelected()) {
            try {
                String search = "select*from books where author like"
                        + "'" + txtAuthor.getText() + "%'";
                ResultSet rs2 = MyConn.search(search);
                df.setRowCount(0);
                while (rs2.next()) {
                    Vector v = new Vector();
                    v.add(rs2.getString("ID"));
                    v.add(rs2.getString("Name"));
                    v.add(rs2.getString("Author"));
                    v.add(rs2.getString("Type"));
                    v.add(rs2.getString("Unit Price"));
                    v.add(rs2.getString("Stock"));
                    df.addRow(v);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (JRB_BType.isSelected()) {
            try {
                String search = "select*from books where type like "
                        + "'" + txtType.getText() + "%'";
                ResultSet rs3 = MyConn.search(search);
                df.setRowCount(0);
                while (rs3.next()) {
                    Vector v = new Vector();
                    v.add(rs3.getString("ID"));
                    v.add(rs3.getString("Name"));
                    v.add(rs3.getString("Author"));
                    v.add(rs3.getString("Type"));
                    v.add(rs3.getString("Unit Price"));
                    v.add(rs3.getString("Stock"));
                    df.addRow(v);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        if (JRB_Bcheap.isSelected()) {
            try {
                String arange = "SELECT * FROM books ORDER BY `Unit Price`";
                ResultSet rsA = MyConn.search(arange);
                df.setRowCount(0);
                while (rsA.next()) {
                    Vector v = new Vector();
                    v.add(rsA.getString("ID"));
                    v.add(rsA.getString("Name"));
                    v.add(rsA.getString("Author"));
                    v.add(rsA.getString("Type"));
                    v.add(rsA.getString("Unit Price"));
                    v.add(rsA.getString("Stock"));
                    df.addRow(v);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else if (JRB_BExpensive.isSelected()) {
            try {
                String arange = "SELECT * FROM books ORDER BY `Unit Price` DESC";
                ResultSet rsA = MyConn.search(arange);
                df.setRowCount(0);
                while (rsA.next()) {
                    Vector v = new Vector();
                    v.add(rsA.getString("ID"));
                    v.add(rsA.getString("Name"));
                    v.add(rsA.getString("Author"));
                    v.add(rsA.getString("Type"));
                    v.add(rsA.getString("Unit Price"));
                    v.add(rsA.getString("Stock"));
                    df.addRow(v);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_JbtnFilterSearch1ActionPerformed

    private void JBTN_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_DashboardActionPerformed
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_JBTN_DashboardActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        txtName.requestFocusInWindow();
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        txtAuthor.requestFocusInWindow();
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorActionPerformed
        txtType.requestFocusInWindow();
    }//GEN-LAST:event_txtAuthorActionPerformed

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        txtPrice.requestFocusInWindow();
    }//GEN-LAST:event_txtTypeActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        txtStock.requestFocusInWindow();
    }//GEN-LAST:event_txtPriceActionPerformed

    private void JRB_BcheapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_BcheapActionPerformed
        buttonGroupSearch.clearSelection();
    }//GEN-LAST:event_JRB_BcheapActionPerformed

    private void JRB_BExpensiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_BExpensiveActionPerformed
        buttonGroupSearch.clearSelection();
    }//GEN-LAST:event_JRB_BExpensiveActionPerformed

    private void JRB_BNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_BNameActionPerformed
        buttonGroupFilter.clearSelection();
    }//GEN-LAST:event_JRB_BNameActionPerformed

    private void JRB_BAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_BAuthorActionPerformed
        buttonGroupFilter.clearSelection();
    }//GEN-LAST:event_JRB_BAuthorActionPerformed

    private void JRB_BTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_BTypeActionPerformed
        buttonGroupFilter.clearSelection();
    }//GEN-LAST:event_JRB_BTypeActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Books().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTN_Dashboard;
    private javax.swing.JRadioButton JRB_BAuthor;
    private javax.swing.JRadioButton JRB_BExpensive;
    private javax.swing.JRadioButton JRB_BName;
    private javax.swing.JRadioButton JRB_BType;
    private javax.swing.JRadioButton JRB_Bcheap;
    private javax.swing.JButton JbtnAccessories;
    private javax.swing.JButton JbtnDelete;
    private javax.swing.JButton JbtnFilterSearch1;
    private javax.swing.JButton JbtnInsert;
    private javax.swing.JButton JbtnInstruments;
    private javax.swing.JButton JbtnPurchase;
    private javax.swing.JButton JbtnUpdate;
    private javax.swing.JTable JtblSearch;
    private javax.swing.ButtonGroup buttonGroupFilter;
    private javax.swing.ButtonGroup buttonGroupIN_UP_DEL;
    private javax.swing.ButtonGroup buttonGroupSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables

    private void search() {
        try {
            DefaultTableModel dfsearch = (DefaultTableModel) JtblSearch.getModel();

            String sqlfirstsearh = "SELECT * FROM lifenotemusiccenter.books";
            ResultSet rsfirstsearch = MyConn.search(sqlfirstsearh);
            dfsearch.setRowCount(0);
            while (rsfirstsearch.next()) {
                Vector vsearch = new Vector();
                vsearch.add(rsfirstsearch.getString("ID"));
                vsearch.add(rsfirstsearch.getString("Name"));
                vsearch.add(rsfirstsearch.getString("Author"));
                vsearch.add(rsfirstsearch.getString("Type"));
                vsearch.add(rsfirstsearch.getString("Unit Price"));
                vsearch.add(rsfirstsearch.getString("Stock"));
                dfsearch.addRow(vsearch);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void searchIN_UP_DEL() {
        try {
            String searchid = "select*from books";
            ResultSet rs = MyConn.search(searchid);
            DefaultTableModel df = (DefaultTableModel) JtblSearch.getModel();
            df.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("ID"));
                v.add(rs.getString("Name"));
                v.add(rs.getString("Author"));
                v.add(rs.getString("Type"));
                v.add(rs.getString("Unit Price"));
                v.add(rs.getString("Stock"));
                df.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void UP_toGRN() {
        try {
            String sqlINUP = "INSERT into grn (`DB Table`, `Item ID`, `Added Stock`,"
                    + "`Other changes_Name`, `Other changese_Brand_Author`,"
                    + "`Other changes_Type`, `Other changes_Unit Price`, `Date and Time`)"
                    + "values('Books','" + txtId.getText() + "','" + txtStock.getText() + "',"
                    + "'" + txtName.getText() + "','" + txtAuthor.getText() + "',"
                    + "'" + txtType.getText() + "','" + txtPrice.getText() + "',current_timestamp)";
            MyConn.save(sqlINUP);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
